# Information about where the book exists on the web
repository:
  url: https://github.com/ubern-mia/bender # Online location of your book
  path_to_book: episode03/dermamnist_v1_initial.ipynb # Optional path to your book, relative to the repository root
  branch: master # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  colab_url: "https://colab.research.google.com"
