name: Check Links

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install lychee
      run: |
        wget https://github.com/lycheeverse/lychee/releases/download/v0.15.0/lychee-v0.15.0-x86_64-unknown-linux-gnu.tar.gz
        tar -xzf lychee-v0.15.0-x86_64-unknown-linux-gnu.tar.gz
        sudo mv lychee /usr/local/bin/

    - name: Check links in Markdown files
      run: lychee --verbose --no-progress --include "https://github.com/ubern-mia/bender/blob/main/**/*.md" --exclude "https://www.youtube.com/**" --exclude-mail **/*.md